### ISSUE TITLE
This seems like my project

### ISSUE THREAD

**Issue by ThoughtfulDev** [CybernetiX-S3C/Facial-Recon-master#1]
Hey @CybernetiX-S3C and @JohnModica ,
this seems like a copy of my project EagleEye - https://github.com/ThoughtfulDev/EagleEye
As a proof there are traces of you changing the name in the commit history on commit 6727a8b8a2471563063ed5a2bb0f9b0993fefee3
![grafik](https://user-images.githubusercontent.com/23433433/50375458-dd596980-05fd-11e9-8721-48d22484a1c1.png)

If you continue this project please kindly say that this is a derivative of mine :) Thanks.

**Comment by CybernetiX-S3C** [comment]
[https://github.com/ThoughtfulDev/EagleEye/blob/master/README.md](url)

**Comment by CybernetiX-S3C** [comment]
Everyone is permitted to copy and distribute verbatim or modified
 copies of this license document, and changing it is allowed as long
 as the name is changed.

            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

  0. You just DO WHAT THE FUCK YOU WANT TO.

**Comment by CybernetiX-S3C** [comment]
Don't come at me sideways, when you clearly state to do whatever you want as long as the name changes.
